#include "JobScheduler.hpp"
#include <sstream>
#include <stdexcept>

namespace taskforge {
const char* to_string(Status s) { switch(s) { case Status::Pending:return "PENDING"; case Status::Blocked:return "BLOCKED"; case Status::Ready:return "READY"; case Status::Running:return "RUNNING"; case Status::Completed:return "COMPLETED"; case Status::Failed:return "FAILED"; case Status::Cancelled:return "CANCELLED"; } return "UNKNOWN"; }
const char* to_string(Priority p) { return p == Priority::High ? "HIGH" : p == Priority::Medium ? "MEDIUM" : "LOW"; }
void MetricsCollector::submitted(){ std::lock_guard<std::mutex> l(mutex_); ++data_.submitted; }
void MetricsCollector::started(std::chrono::milliseconds wait){ std::lock_guard<std::mutex> l(mutex_); ++data_.running; data_.peak_running=std::max(data_.peak_running,data_.running); data_.total_wait+=wait; }
void MetricsCollector::finished(bool ok,std::chrono::milliseconds run){ std::lock_guard<std::mutex> l(mutex_); --data_.running; ok ? ++data_.completed : ++data_.failed; data_.total_run+=run; }
void MetricsCollector::retried(){ std::lock_guard<std::mutex> l(mutex_); --data_.running; ++data_.retries; }
Metrics MetricsCollector::snapshot() const { std::lock_guard<std::mutex> l(mutex_); return data_; }

JobScheduler::JobScheduler(std::size_t workers,std::unique_ptr<SchedulingStrategy> strategy):strategy_(std::move(strategy)),worker_count_(workers) { if(!worker_count_ || !strategy_) throw std::invalid_argument("workers and strategy are required"); }
JobScheduler::~JobScheduler(){ stop(); }
bool JobScheduler::cycle_if_added_locked(const Job& c) const { std::unordered_map<JobId,std::vector<JobId>> edges=dependents_; for(const auto& d:c.dependencies) edges[d].push_back(c.id); std::unordered_map<JobId,int> color; std::function<bool(const JobId&)> dfs=[&](const JobId& n){ if(color[n]==1)return true; if(color[n]==2)return false; color[n]=1; for(const auto& v:edges[n]) if(dfs(v))return true; color[n]=2; return false; }; for(const auto& [id,_]:jobs_) if(dfs(id))return true; return dfs(c.id); }
void JobScheduler::add(Job j) { std::lock_guard<std::mutex> l(mutex_); if(started_) throw std::logic_error("cannot add jobs after start"); if(j.id.empty()||!j.task) throw std::invalid_argument("job needs an id and task"); if(jobs_.count(j.id)) throw std::invalid_argument("duplicate job id: "+j.id); if(cycle_if_added_locked(j)) throw std::invalid_argument("dependency cycle detected"); j.submitted_at=std::chrono::steady_clock::now(); const auto id=j.id; jobs_.emplace(id,std::move(j)); submission_order_.push_back(id); for(const auto& d:jobs_.at(id).dependencies) dependents_[d].push_back(id); metrics_.submitted(); }
void JobScheduler::evaluate_locked(const JobId& id) { auto& j=jobs_.at(id); if(j.status==Status::Ready||j.status==Status::Running||j.status==Status::Completed||j.status==Status::Failed||j.status==Status::Cancelled)return; bool blocked=false; for(const auto& d:j.dependencies){ auto s=jobs_.at(d).status; if(s==Status::Failed||s==Status::Cancelled){j.status=Status::Cancelled; for(const auto& next:dependents_[id])evaluate_locked(next); return;} if(s!=Status::Completed)blocked=true; } if(blocked){j.status=Status::Blocked; return;} j.status=Status::Ready; strategy_->push(id,j.priority,order_++); cv_.notify_one(); }
void JobScheduler::start(){ std::lock_guard<std::mutex> l(mutex_); if(started_)throw std::logic_error("scheduler already started"); for(const auto& [id,j]:jobs_) for(const auto& dependency:j.dependencies) if(!jobs_.count(dependency)) throw std::invalid_argument("missing dependency for "+id+": "+dependency); started_=true; for(const auto& id:submission_order_) evaluate_locked(id); for(std::size_t i=0;i<worker_count_;++i) workers_.emplace_back(&JobScheduler::worker,this); }
bool JobScheduler::terminal_locked() const { for(const auto& [_,j]:jobs_) if(j.status!=Status::Completed&&j.status!=Status::Failed&&j.status!=Status::Cancelled)return false; return active_==0; }
void JobScheduler::worker(){ for(;;){ JobId id; JobFunction fn; std::chrono::steady_clock::time_point started; { std::unique_lock<std::mutex> l(mutex_); cv_.wait(l,[&]{return stopping_||!strategy_->empty()||terminal_locked();}); if(stopping_ || (strategy_->empty()&&terminal_locked()))return; id=strategy_->pop(); auto& j=jobs_.at(id); if(j.status!=Status::Ready)continue; j.status=Status::Running; started=j.started_at=std::chrono::steady_clock::now(); ++active_; metrics_.started(std::chrono::duration_cast<std::chrono::milliseconds>(started-j.submitted_at)); fn=j.task; } bool ok=false; try {ok=fn();}catch(...){ok=false;} auto end=std::chrono::steady_clock::now(); complete(id,ok,std::chrono::duration_cast<std::chrono::milliseconds>(end-started)); } }
void JobScheduler::complete(const JobId& id,bool ok,std::chrono::milliseconds dur){ std::lock_guard<std::mutex> l(mutex_); auto& j=jobs_.at(id); --active_; j.run_time=dur; if(ok){j.status=Status::Completed;metrics_.finished(true,dur); for(const auto& next:dependents_[id])evaluate_locked(next);} else if(j.retries<j.max_retries){++j.retries; j.status=Status::Ready;strategy_->push(id,j.priority,order_++);metrics_.retried();cv_.notify_one();}else{j.status=Status::Failed;metrics_.finished(false,dur);for(const auto& next:dependents_[id])evaluate_locked(next);} if(terminal_locked()){done_cv_.notify_all();cv_.notify_all();} }
void JobScheduler::wait(){ std::unique_lock<std::mutex> l(mutex_); if(!started_)throw std::logic_error("scheduler not started"); done_cv_.wait(l,[&]{return terminal_locked()||stopping_;}); }
void JobScheduler::stop(){ {std::lock_guard<std::mutex> l(mutex_); if(stopping_){} else {stopping_=true; for(auto& [_,j]:jobs_) if(j.status==Status::Pending||j.status==Status::Blocked||j.status==Status::Ready)j.status=Status::Cancelled;} } cv_.notify_all(); done_cv_.notify_all(); for(auto& t:workers_)if(t.joinable())t.join(); workers_.clear(); }
Status JobScheduler::status(const JobId& id)const{std::lock_guard<std::mutex>l(mutex_);return jobs_.at(id).status;}
Job JobScheduler::job(const JobId& id)const{std::lock_guard<std::mutex>l(mutex_);return jobs_.at(id);}
Metrics JobScheduler::metrics()const{return metrics_.snapshot();}
std::string JobScheduler::summary()const{auto m=metrics();auto done=m.completed+m.failed;std::ostringstream o;o<<"========= Execution Summary =========\nJobs submitted: "<<m.submitted<<"\nJobs completed: "<<m.completed<<"\nJobs failed: "<<m.failed<<"\nRetries: "<<m.retries<<"\nAverage wait time: "<<(done?m.total_wait.count()/done:0)<<" ms\nAverage run time: "<<(done?m.total_run.count()/done:0)<<" ms\nPeak concurrent jobs: "<<m.peak_running<<"\n";return o.str();}
}
